server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

cloud:
  gateway:
    routes:
      - id: tour-planning
        uri: lb://tour-planning
        predicates:
          - Path=/tour-planning/**
